export const nbaLogos = {
  Atlanta: 'src/assets/Logos/Atlanta-Hawks-Logo.png',
  Boston: 'src/assets/Logos/Boston-Celtics-Logo.png',
  Brooklyn: 'src/assets/Logos/Brooklyn-Nets-Logo.png',
  Charlotte: 'src/assets/Logos/Charlotte-Hornets-Logo.png',
  Chicago: 'src/assets/Logos/Chicago-Bulls-Logo.png',
  Cleveland: 'src/assets/Logos/Cleveland-Cavaliers-Logo.png',
  Dallas: 'src/assets/Logos/Dallas-Mavericks-Logo.png',
  Denver: 'src/assets/Logos/Denver-Nuggets-Logo.png',
  Detroit: 'src/assets/Logos/Detroit-Pistons-Logo.png',
  'Golden State': 'src/assets/Logos/Golden-State-Warriors-Logo.png',
  Houston: 'src/assets/Logos/Houston-Rockets-Logo.png',
  Indiana: 'src/assets/Logos/Indianapolis-Pacers-Logo.png',
  LA: 'src/assets/Logos/Los-Angeles-Clippers-Logo.png',
  'Los Angeles': 'src/assets/Logos/Los-Angeles-Lakers-Logo.png',
  Memphis: 'src/assets/Logos/Memphis-Grizzlies-Logo.png',
  Miami: 'src/assets/Logos/Miami-Heat-Logo.png',
  Milwaukee: 'src/assets/Logos/Milwaukee-Bucks-Logo.png',
  Minnesota: 'src/assets/Logos/Minnesota-Timberwolves-Logo.png',
  'New Orleans': 'src/assets/Logos/New-Orleans-Pelicans-Logo.png',
  'New York': 'src/assets/Logos/New-York-Knicks-Logo.png',
  'Oklahoma City': 'src/assets/Logos/Oklahoma-City-Thunder-Logo.png',
  Orlando: 'src/assets/Logos/Orlando-Magic-Logo.png',
  Philadelphia: '/src/assets/Logos/76ers.svg',
  Phoenix: 'src/assets/Logos/Phoenix-Suns-Logo.png',
  Portland: 'src/assets/Logos/Portland-Trail-Blazers-Logo.png',
  Sacramento: 'src/assets/Logos/Sacramento-Kings-Logo.png',
  'San Antonio': 'src/assets/Logos/San-Antonio-Spurs-Logo.png',
  Toronto:
    'http://localhost:8011/proxy/logos/nba/1610612761/primary/L/logo.svg',
  Utah: 'src/assets/Logos/Utah-Jazz-Logo.png',
  Washington: 'src/assets/Logos/Washington-Wizards-Logo.png',
};

//Philadelphia: 'src/assets/Logos/Philadephia-76ers-Logo.png',
